### PR TITLE
chore: update SDK from api-definitions

### LINKED ISSUE #675: Do convert array of objects to array of arrays on call `jsonSerialize()`
SDK Version: 3.0.0

Some model fields are arrays of other objects. And when `$model->jsonSerialize()` is called, these arrays of objects aren't converted to JSON arrays, but remain objects.

[Customer::jsonSerialize()](https://github.com/Rebilly/rebilly-php/blob/5023da87390b9491edecbd83f54bfb3726ee4698/src/Model/Customer.php#L413):

```php
// ...
if (array_key_exists('tags', $this->fields)) {
    $data['tags'] = $this->fields['tags'];
}
```

[ContactObject::jsonSerialize()](https://github.com/Rebilly/rebilly-php/blob/5023da87390b9491edecbd83f54bfb3726ee4698/src/Model/ContactObject.php#L292):

```php
if (array_key_exists('phoneNumbers', $this->fields)) {
    $data['phoneNumbers'] = $this->fields['phoneNumbers'];
}
if (array_key_exists('emails', $this->fields)) {
    $data['emails'] = $this->fields['emails'];
}
```

Therefore a call `$customer->jsonSerialize()` returns (partially):

```
array:23 [
  "id" => "085e96b4-7f64-411b-9307-4b627f2b3007"
  "websiteId" => "example.com"
  "createdTime" => "2020-09-13T20:05:08+00:00"
  "updatedTime" => "2021-12-03T11:20:38+00:00"
  "customFields" => []
  "primaryAddress" => array:14 [
    "city" => "City 1"
    "region" => "State"
    "country" => "AF"
    "postalCode" => "111222"
    "phoneNumbers" => array:1 [
      0 => Rebilly\Sdk\Model\ContactPhoneNumbers^ {#2667
        -fields: array:3 [
          "label" => "Main"
          "value" => "+1234567890"
          "primary" => true
        ]
      }
    ]
    "emails" => array:1 [
      0 => Rebilly\Sdk\Model\ContactEmails^ {#2663
        -fields: array:3 [
          "label" => "Main"
          "value" => "...@example.com"
          "primary" => true
        ]
      }
    ]
  ]
  "tags" => array:1 [
    0 => Rebilly\Sdk\Model\Tag^ {#2658
      -fields: array:5 [
        "id" => "3759a810-f836-436c-ae8c-40f5e0ff4efe"
        "name" => "notes"
        "type" => "customer"
        "createdTime" => DateTimeImmutable @1623769937 {#2643
          date: 2021-06-15 15:12:17.0 +00:00
        }
        "updatedTime" => DateTimeImmutable @1623769937 {#2657
          date: 2021-06-15 15:12:17.0 +00:00
        }
      ]
    }
  ]
```

But all these objects in the subarrays must also be plain arrays.

I suggest fixing your PHP code generators to produce code like this:

```php
$data['phoneNumbers'] = array_map(fn ($v) => $v->jsonSerialize(), $this->fields['phoneNumbers']);
```

### PR DESCRIPTION
**Pull request by ghost**
This PR is automatically generated and updates SDK based on a change in the API definitions

Resolves https://github.com/Rebilly/rebilly-php/issues/675

### CODE REVIEW

**Comment by rebilly-machine-user** [comment]
- Fix filter and collection docs links Rebilly/api-definitions#1868 [edit changeset](https://github.com/Rebilly/rebilly-php/edit/automations/update-sdk-from-api-definitions/.changeset/twenty-paws-grin.md?pr=%2FRebilly%2Frebilly-php%2Fpull%2F684)

**Review by ashkarpetin — DISMISSED** [review]

**Review by justnero — APPROVED** [review]

**Comment by justnero** [comment]
Issue, mentioned in https://github.com/Rebilly/rebilly-php/pull/684#issuecomment-2050439502 was resolved, please review

**Comment by ashkarpetin** [comment]
What abount `collectionExpand` which is not consistent with `collectionSort`?

**Comment by justnero** [comment]
@ashkarpetin has to be done separately to keep diff manageable

**Review by ashkarpetin — APPROVED** [review]

**Pull request merged**
