### PR TITLE
Add disputeTime to Transaction

### PR DESCRIPTION
**Pull request by truechernyshov**

### CODE REVIEW

**Comment by adamaltman** [comment]
If this exists, it is not in our API definitions. https://www.rebilly.com/docs/developer-docs/api/operation/GetTransaction/ 

It should have been added there.

**Comment by adamaltman** [comment]
Looking inside the code I also see `'disputeStatus'` too. API definitions should be adjusted to reflect both of these `readOnly` properties.

**Comment by alekseyp** [comment]
Does api-definitions#369 needs to be merged first or current changed can be merged into sdk beforehand?

**Review by slavcodev — APPROVED** [review]

**Comment by slavcodev** [comment]
@Rebilly/php please review

**Comment by slavcodev** [comment]
@alekseyp will merge both asap

**Review by colinbird — APPROVED** [review]

**Review by vykhrystiuk — APPROVED** [review]

**Comment by slavcodev** [comment]
Thank you @truechernyshov for the contribution.

**Pull request merged**
