### PR TITLE
Sessions API

### PR DESCRIPTION
**Pull request by XaosSintez**

### CODE REVIEW

**Comment by adamaltman** [comment]
What about a mechanism for using a session token for authentication (eg, instead of the private key)?

**Comment by slavcodev** [comment]
That's mechanism can be added in separate PR. This one seems ok, just a note, some tests would be useful, the coverage decreased -4.4% only w/ this PR, it's not good.

**Comment by XaosSintez** [comment]
I will add some tests, thanks!

**Comment by XaosSintez** [comment]
@adamaltman It will be separate PR, i'm going to make it today

**Comment by slavcodev** [comment]
OK, merged. Tests also you can add in new PR.

**Pull request merged**
