### PR TITLE
Add PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by dortort**
Adds type definitions required by PHP 8.1.

### CODE REVIEW

**Review by colinbird — DISMISSED** [review]

**Comment by slavcodev** [comment]
Are you going to allow it in `composer.json`, `CHANGELOG`?
Also this is break-compatibility change, so probably will require to bump major version of SDK.

**Comment by ashkarpetin** [comment]
What about updating workflow.yml to enable 8.1 unit tests?

**Comment by dortort** [comment]
> Are you going to allow it in `composer.json`, `CHANGELOG`?
> Also this is break-compatibility change, so probably will require to bump major version of SDK.

Looks like it's already allowed:
https://github.com/Rebilly/rebilly-php/blob/43a9a70fdd2a1d318975e9642e1a9b3617f4a465/composer.json#L21

If the changes are backwards-compatible, a major bump shouldn't be required, no?

**Comment by slavcodev** [comment]
> Looks like it's already allowed

Oops, have not noticed the `>` is used, rather and SemVer.

> If the changes are backwards-compatible, a major bump shouldn't be required, no?

In theory they are not `backwards-compatible` I think. If someone inherit one of this class and already set "not-compatible" return type, that will throw error.

**Review by colinbird — APPROVED** [review]

**Review by ninjasimon — APPROVED** [review]

**Comment by ashkarpetin** [comment]
I think we to update changelog

**Review by wmdmgv — APPROVED** [review]

**Pull request merged**
